### PR TITLE
Setting of folder permissions through Hadoop FileUtil class

### PR DESCRIPTION
**Pull request by oleksandr-yatsuk**
Due to the issue that **file.setWritable(true, false)** method returns false on WIndows the way how the folder is setting writable changed.
Hadoop FileUtil method used instead.

### CODE REVIEW

**Comment by PelleUllberg** [comment]
Hi, Sorry for the late reply.

First let me say I'm really happy to have a microsoft user trying to fix the OS related problems.

What's the motivation for the class HiveFolder as opposite to just inlining the logic?

regards
/Pelle

**Comment by oleksandr-yatsuk** [comment]
Hi,

Yes, the main purpose of the HiveFolder inline the logic of setting the permissions.
Because it is used in multiple places I decided to put it into the separate class.
As an oposite to the approach above we can put the logic into the static method etc

**Comment by oleksandr-yatsuk** [comment]
Pelle, 

Also regarding to my prev comment I would like to add that HiveFolder it is not just a writable folder, it is a folder with all permissions needed to use it as a storage base. 
And Hadoop internally checks whether a folder has permissions, not only if it is writable or not

**Comment by PelleUllberg** [comment]
I don't think such few lines of code duplication even justifies a static method to get rid of the duplication. Just inline them where they're needed. 

Also, my guess is that FileUtil.setPermission(folder, writablePermission); will throw an IOE if the permission may not be set? In that case, the assert may be removed and it's only a one liner?

**Comment by oleksandr-yatsuk** [comment]
Yes, you are right.
I chacked out the source of FileUtil.setPermission method and it will just throw an exception in case permission is not set.
So the assert may be replaced with FilUtil.setPermission line

**Comment by PelleUllberg** [comment]
Awesome, If you could just update the changelog in the README I'll approve and merge it.

**Comment by PelleUllberg** [comment]
Thanks a bunch. I'll merge it! Welcome!

**Comment by oleksandr-yatsuk** [comment]
Thank you 👍

**Comment by oleksandr-yatsuk** [comment]
Pelle, one question: when are you going to release the version 3.2.1 ?
Because I changed the change log but didn't update the version in pom.xml file.

**Comment by PelleUllberg** [comment]
Ahh, it should probably have said 3.2.1-SNAPSHOT in the change log until we release it. I'll try to get it released sometime this week.

/Pelle

**Comment by oleksandr-yatsuk** [comment]
OK, thank you

**Comment by APTomlinson** [comment]
Hi - @PelleUllberg, is there any update on the 3.2.1 release?

**Comment by zhaolihe** [comment]
which tag is release for this issue.

**Comment by zhaolihe** [comment]
i am download sourcecode and reference,but get exception
``` java
java.lang.IllegalStateException: Failed to create HiveServer :java.lang.RuntimeException: The root scratch dir: C:/Users/ADMINI~1/AppData/Local/Temp/junit2186001686892593445/scratchdir on HDFS should be writable. Current permissions are: rw-rw-rw-

	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:102)
	at com.klarna.hiverunner.builder.HiveShellBase.start(HiveShellBase.java:150)
	at com.klarna.hiverunner.StandaloneHiveRunner.createHiveServerContainer(StandaloneHiveRunner.java:221)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:173)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:62)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:89)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: The root scratch dir: C:/Users/ADMINI~1/AppData/Local/Temp/junit2186001686892593445/scratchdir on HDFS should be writable. Current permissions are: rw-rw-rw-
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:540)
	at org.apache.hive.service.cli.CLIService.applyAuthorizationConfigPolicy(CLIService.java:124)
	at org.apache.hive.service.cli.CLIService.init(CLIService.java:111)
	at org.apache.hive.service.CompositeService.init(CompositeService.java:59)
	at org.apache.hive.service.server.HiveServer2.init(HiveServer2.java:123)
	at com.klarna.hiverunner.HiveServerContainer.init(HiveServerContainer.java:85)
	... 8 more
Caused by: java.lang.RuntimeException: The root scratch dir: C:/Users/ADMINI~1/AppData/Local/Temp/junit2186001686892593445/scratchdir on HDFS should be writable. Current permissions are: rw-rw-rw-
	at org.apache.hadoop.hive.ql.session.SessionState.createRootHDFSDir(SessionState.java:625)
	at org.apache.hadoop.hive.ql.session.SessionState.createSessionDirs(SessionState.java:574)
	at org.apache.hadoop.hive.ql.session.SessionState.start(SessionState.java:518)
	... 13 more

```
@oleksandr-yatsuk  any idea to resolve it , now my window system does not config HADOOP_HOME 
 in environment variable

**Comment by oleksandr-yatsuk** [comment]
To make it work on Windows you should use Windows compatible WinUtils.exe file and another libs.
I use https://github.com/sakserv/hadoop-mini-clusters/tree/master/windows_libs/2.5.0.0.
Then you should run tests with JVM options **java.library.path** and **hadoop.home.dir** pointing to the folder with windows libs

**Comment by oleksandr-yatsuk** [comment]
this is the example of argLine of **maven-sure-fire-plugin**: -Xmx2048m -Djava.library.path=./../windows_libs/lib/ -Dhadoop.home.dir=./../windows-libs/

**Comment by zhaolihe** [comment]
very good. now my unit test can past.
by the way, do you have unit test like this ` insert into target_table from select columns from source_table`. this type of test can not past in Windows. the exception message is 
``` java 

java.lang.IllegalArgumentException: Failed to executeQuery Hive query insert into test.result select year,max(value) from test.test_table group by year: Error while processing statement: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z

	at com.klarna.hiverunner.HiveServerContainer.executeStatement(HiveServerContainer.java:144)
	at com.klarna.hiverunner.HiveServerContainer.executeScript(HiveServerContainer.java:156)
	at com.klarna.hiverunner.builder.HiveShellBase.executeScriptWithCommandShellEmulation(HiveShellBase.java:326)
	at com.klarna.hiverunner.builder.HiveShellBase.execute(HiveShellBase.java:113)
	at com.yoyi.data.hive.HiveRunnerTest.testMaxCountByYear(HiveRunnerTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.klarna.hiverunner.StandaloneHiveRunner.evaluateStatement(StandaloneHiveRunner.java:174)
	at com.klarna.hiverunner.StandaloneHiveRunner.access$000(StandaloneHiveRunner.java:62)
	at com.klarna.hiverunner.StandaloneHiveRunner$1$1.evaluate(StandaloneHiveRunner.java:89)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at com.klarna.hiverunner.ThrowOnTimeout$1.run(ThrowOnTimeout.java:42)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
	at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:374)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:180)
	at org.apache.hive.service.cli.operation.SQLOperation.runInternal(SQLOperation.java:208)
	at org.apache.hive.service.cli.operation.Operation.run(Operation.java:316)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatementInternal(HiveSessionImpl.java:424)
	at org.apache.hive.service.cli.session.HiveSessionImpl.executeStatement(HiveSessionImpl.java:395)
	at org.apache.hive.service.cli.CLIService.executeStatement(CLIService.java:245)
	at com.klarna.hiverunner.HiveServerContainer.executeStatement(HiveServerContainer.java:117)
	... 19 more
Caused by: java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
	at org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Native Method)
	at org.apache.hadoop.io.nativeio.NativeIO$Windows.access(NativeIO.java:609)
	at org.apache.hadoop.fs.FileUtil.canRead(FileUtil.java:980)
	at org.apache.hadoop.util.DiskChecker.checkAccessByFileMethods(DiskChecker.java:187)
	at org.apache.hadoop.util.DiskChecker.checkDirAccess(DiskChecker.java:174)
	at org.apache.hadoop.util.DiskChecker.checkDir(DiskChecker.java:108)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.confChanged(LocalDirAllocator.java:314)
	at org.apache.hadoop.fs.LocalDirAllocator$AllocatorPerContext.getLocalPathForWrite(LocalDirAllocator.java:377)
	at org.apache.hadoop.fs.LocalDirAllocator.getLocalPathForWrite(LocalDirAllocator.java:151)
	at org.apache.hadoop.fs.LocalDirAllocator.getLocalPathForWrite(LocalDirAllocator.java:132)
	at org.apache.hadoop.fs.LocalDirAllocator.getLocalPathForWrite(LocalDirAllocator.java:116)
	at org.apache.hadoop.mapred.LocalDistributedCacheManager.setup(LocalDistributedCacheManager.java:125)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.<init>(LocalJobRunner.java:171)
	at org.apache.hadoop.mapred.LocalJobRunner.submitJob(LocalJobRunner.java:758)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:244)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1307)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1304)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1304)
	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:578)
	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:573)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:573)
	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:564)
	at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(ExecDriver.java:429)
	at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(MapRedTask.java:137)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:160)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:100)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1782)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1539)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1318)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1127)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1120)
	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:178)
	... 25 more
```

**Comment by oleksandr-yatsuk** [comment]
It seems that you still have the problem with access to the file system.
Before run a unit tests just try to re-set **hadoop.home.dir** variable at runtime.
Please, keep in mind that the path must be unix-like.

Below is the code snippet:

String hadoopHome = System.getProperty("hadoop.home.dir");
File hadoopHomeFile = new File(hadoopHome);

String path = hadoopHomeFile .getCanonicalPath(); // Gives you a full path, not the relative one
String unixLikePath = org.apache.commons.io.FilenameUtils.separatorsToUnix(path);

System.setProperty("hadoop.home.dir", unixLikePath);

You should run this code once at the early beginning, for example in static inializer (block) of the base test

static { //execute code }

**Comment by zhaolihe** [comment]
@oleksandr-yatsuk  i have do as what you say. but the exception still exists,
my code snippet is
 ```java
 static {
        System.setProperty("java.library.path",HiveRunnerTest.class.getResource("/windows_libs/lib").getPath());
        System.setProperty("hadoop.home.dir",HiveRunnerTest.class.getResource("/windows_libs").getPath());
        String hadoopHome = System.getProperty("hadoop.home.dir");
        File hadoopHomeFile = new File(hadoopHome);
        String path = null; // Gives you a full path, not the relative one
        try {
            path = hadoopHomeFile .getCanonicalPath();
            String unixLikePath = org.apache.commons.io.FilenameUtils.separatorsToUnix(path);
            System.setProperty("hadoop.home.dir", unixLikePath);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

 @Test
    public void testMaxCountByYear() {
        shell.execute(new StringBuilder().append("create table test.test_table(")
                .append("year STRING,value INT)").toString());
        shell.insertInto("test", "test_table").withColumns("year", "value")
                .addRow("2017", "4")
                .addRow("2016", "5")
                .addRow("2015", "3")
                .addRow("2014", "7")
                .addRow("2016", "1")
                .addRow("2015", "2")
                .commit();
        String sqlScript = "create table test.result(year STRING,maxValue INT)";
        shell.execute(sqlScript);
        shell.execute("select year,max(value) from test.test_table group by year");
        shell.execute(" insert into test.result select year,max(value) from test.test_table group by year");
        List<Object[]> result = shell.executeStatement("select * from test.result where year = '2017'");
        assertNotNull(result);
        assertArrayEquals(new Object[]{"2017", 4}, result.get(0));
    }
```
any idea about it

**Comment by oleksandr-yatsuk** [comment]
If you are setting **java.library.path** at runtime it is not going to work (you need to do some hack to be able to modify it at runtime)
Please check that you are running the test:
1) With JVM option **java.library.path**
2) With JVM option **hadoop.home.dir** with full, unix like path (not relative) pointing to the folder /windows_libs **OR** with JVM option  **hadoop.home.dir** pointing to the relative path of /windows_libs and change it to full, unix like path at runtime (as I do in the code snippet above)

**Comment by zhaolihe** [comment]
@oleksandr-yatsuk  i do as what you say, but running unit test occur the same exception also.  my operation like : 
* edit unit test Configurations, add VM options `-Djava.library.path=./../windows_libs/lib/ -Dhadoop.home.dir=./../windows-libs/`
* modify relative path to full,unix like path in static constructor like the code snippet you write above
* do my unit test,but the same exception as above occur.

**Comment by oleksandr-yatsuk** [comment]
Ok, there is might be another problem.
Could you try to check/set the permissions of any folder on your computer with **WinUtils.exe** from windows_libs: **winutils.exe chmod 777 [folder_path]**
Why I am asking to the above because if your computer is in domain you may encounter with the issue https://support.microsoft.com/en-us/help/2771040/-the-trust-relationship-between-this-workstation-and-the-primary-domain-failed-error-when-you-log-on-to-a-computer-that-is-running-windows-7

**Comment by raymondcg** [comment]
Hi - @PelleUllberg, is there any update on the 3.2.1 release?

**Comment by skkmca** [comment]
Hi, I was able to run the test cases successfully, however today my machine was restarted and I am not able to run any of the test cases. I am not able to set the winutils.exe to chmod 777 as Access is denied.

Also I am getting the error message as 
ERROR   [InsertTestData#insertRowsFromCode]    org.apache.hadoop.util.Shell    - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.

**Comment by skkmca** [comment]
Please help me what to do. Only SYSTEM ADMIN can able to run this. As due to company policy I am not able to provide full permission to run WINUTILS. Please suggest

**Comment by massdosage** [comment]
HiveRunner 3.2.1 was released and contains this fix.

**Pull request merged**
